language: python
sudo: false
python:
    - "2.7"
    - "3.4"
    - "3.5"
    - "3.6"
    - "pypy-5.3.1"
install:
    - pip install .
    - pip install -U setuptools
    - pip install -r test_requirements.txt
    - ls
script:
    - make tests
    - make cov
after_success:
    - coveralls
